[book]
authors = ["Proudmuslim"]
language = "en"
multilingual = false
src = "src"
title = "Octocat-rs: Beginner's Documentation"

[build]
create-missing = true

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"

[output]

[output.html]
additional-css = ["././mdbook-admonish.css"]
